name: whitesur-gtk-theme # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.2' # just for humans, typically '1.2+git' or '1.3.2'
architectures:
  - build-on: [amd64, arm64]
summary: WiteSur snap port. # 79 char long summary
description: |
  WhiteSur is a MacOS Big Sur like theme for GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 
  based desktop environments like Gnome, Pantheon, XFCE, Mate, Icons etc.

  Port based on the theme ports from Genadi Naydenov (gantonayde).

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/WhiteSur-light
        - $SNAP/share/gtk2/WhiteSur-light-alt
        - $SNAP/share/gtk2/WhiteSur-dark
        - $SNAP/share/gtk2/WhiteSur-dark-alt
        - $SNAP/share/gtk2/WhiteSur-light-solid
        - $SNAP/share/gtk2/WhiteSur-light-solid-alt
        - $SNAP/share/gtk2/WhiteSur-dark-solid
        - $SNAP/share/gtk2/WhiteSur-dark-solid-alt
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/WhiteSur-light
        - $SNAP/share/themes/WhiteSur-light-alt
        - $SNAP/share/themes/WhiteSur-dark
        - $SNAP/share/themes/WhiteSur-dark-alt
        - $SNAP/share/themes/WhiteSur-light-solid
        - $SNAP/share/themes/WhiteSur-light-solid-alt
        - $SNAP/share/themes/WhiteSur-dark-solid
        - $SNAP/share/themes/WhiteSur-dark-solid-alt
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/WhiteSur
        - $SNAP/share/icons/WhiteSur-dark
        
parts:
  whitesur-gtk-theme:
    # See 'snapcraft plugins'
    after: [utils]
    plugin: nil
    source: https://github.com/vinceliuice/WhiteSur-gtk-theme.git
    source-type: git 
    build-packages:
      - sassc
      - libcanberra-gtk-module 
      - libglib2.0-dev
    override-build: |
        snapcraftctl build
        snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
        ./install.sh --dest $SNAPCRAFT_PART_INSTALL/share/themes
        $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*

    # icon theme
  whitesur-icon-theme:
    after: [utils]
    plugin: nil
    source: https://github.com/vinceliuice/WhiteSur-icon-theme.git
    source-type: git 
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
        ./install.sh -d $SNAPCRAFT_PART_INSTALL/share/icons
        $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/WhiteSur*


  utils:
    plugin: dump
    source: utils
    prime:
      - .*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
