name: whitesur-gtk-theme # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '3.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: WiteSur snap port. # 79 char long summary
architectures:
  - build-on: amd64
    run-on: all
description: |
  WhiteSur is a MacOS Big Sur like theme for GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 
  based desktop environments like Gnome, Pantheon, XFCE, Mate, Icons etc.

  Port based on the theme ports from Genadi Naydenov (gantonayde).

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/WhiteSur-light
        - $SNAP/share/gtk2/WhiteSur-light-blue
        - $SNAP/share/gtk2/WhiteSur-light-purple
        - $SNAP/share/gtk2/WhiteSur-light-pink
        - $SNAP/share/gtk2/WhiteSur-light-red
        - $SNAP/share/gtk2/WhiteSur-light-orange
        - $SNAP/share/gtk2/WhiteSur-light-yellow
        - $SNAP/share/gtk2/WhiteSur-light-green
        - $SNAP/share/gtk2/WhiteSur-light-grey
        - $SNAP/share/gtk2/WhiteSur-light-alt
        - $SNAP/share/gtk2/WhiteSur-light-alt-blue
        - $SNAP/share/gtk2/WhiteSur-light-alt-purple
        - $SNAP/share/gtk2/WhiteSur-light-alt-pink
        - $SNAP/share/gtk2/WhiteSur-light-alt-red
        - $SNAP/share/gtk2/WhiteSur-light-alt-orange
        - $SNAP/share/gtk2/WhiteSur-light-alt-yellow
        - $SNAP/share/gtk2/WhiteSur-light-alt-green
        - $SNAP/share/gtk2/WhiteSur-light-alt-grey
        - $SNAP/share/gtk2/WhiteSur-light-solid
        - $SNAP/share/gtk2/WhiteSur-light-solid-blue
        - $SNAP/share/gtk2/WhiteSur-light-solid-purple
        - $SNAP/share/gtk2/WhiteSur-light-solid-pink
        - $SNAP/share/gtk2/WhiteSur-light-solid-red
        - $SNAP/share/gtk2/WhiteSur-light-solid-orange
        - $SNAP/share/gtk2/WhiteSur-light-solid-yellow
        - $SNAP/share/gtk2/WhiteSur-light-solid-green
        - $SNAP/share/gtk2/WhiteSur-light-solid-grey
        - $SNAP/share/gtk2/WhiteSur-light-solid-alt
        - $SNAP/share/gtk2/WhiteSur-light-solid-alt-blue
        - $SNAP/share/gtk2/WhiteSur-light-solid-alt-purple
        - $SNAP/share/gtk2/WhiteSur-light-solid-alt-pink
        - $SNAP/share/gtk2/WhiteSur-light-solid-alt-red
        - $SNAP/share/gtk2/WhiteSur-light-solid-alt-orange
        - $SNAP/share/gtk2/WhiteSur-light-solid-alt-yellow
        - $SNAP/share/gtk2/WhiteSur-light-solid-alt-green
        - $SNAP/share/gtk2/WhiteSur-light-solid-alt-grey
        - $SNAP/share/gtk2/WhiteSur-dark
        - $SNAP/share/gtk2/WhiteSur-dark-blue
        - $SNAP/share/gtk2/WhiteSur-dark-purple
        - $SNAP/share/gtk2/WhiteSur-dark-pink
        - $SNAP/share/gtk2/WhiteSur-dark-red
        - $SNAP/share/gtk2/WhiteSur-dark-orange
        - $SNAP/share/gtk2/WhiteSur-dark-yellow
        - $SNAP/share/gtk2/WhiteSur-dark-green
        - $SNAP/share/gtk2/WhiteSur-dark-grey
        - $SNAP/share/gtk2/WhiteSur-dark-alt
        - $SNAP/share/gtk2/WhiteSur-dark-alt-blue
        - $SNAP/share/gtk2/WhiteSur-dark-alt-purple
        - $SNAP/share/gtk2/WhiteSur-dark-alt-pink
        - $SNAP/share/gtk2/WhiteSur-dark-alt-red
        - $SNAP/share/gtk2/WhiteSur-dark-alt-orange
        - $SNAP/share/gtk2/WhiteSur-dark-alt-yellow
        - $SNAP/share/gtk2/WhiteSur-dark-alt-green
        - $SNAP/share/gtk2/WhiteSur-dark-alt-grey
        - $SNAP/share/gtk2/WhiteSur-dark-solid
        - $SNAP/share/gtk2/WhiteSur-dark-solid-blue
        - $SNAP/share/gtk2/WhiteSur-dark-solid-purple
        - $SNAP/share/gtk2/WhiteSur-dark-solid-pink
        - $SNAP/share/gtk2/WhiteSur-dark-solid-red
        - $SNAP/share/gtk2/WhiteSur-dark-solid-orange
        - $SNAP/share/gtk2/WhiteSur-dark-solid-yellow
        - $SNAP/share/gtk2/WhiteSur-dark-solid-green
        - $SNAP/share/gtk2/WhiteSur-dark-solid-grey
        - $SNAP/share/gtk2/WhiteSur-dark-solid-alt
        - $SNAP/share/gtk2/WhiteSur-dark-solid-alt-blue
        - $SNAP/share/gtk2/WhiteSur-dark-solid-alt-purple
        - $SNAP/share/gtk2/WhiteSur-dark-solid-alt-pink
        - $SNAP/share/gtk2/WhiteSur-dark-solid-alt-red
        - $SNAP/share/gtk2/WhiteSur-dark-solid-alt-orange
        - $SNAP/share/gtk2/WhiteSur-dark-solid-alt-yellow
        - $SNAP/share/gtk2/WhiteSur-dark-solid-alt-grey
        - $SNAP/share/gtk2/WhiteSur-dark-solid-alt-green
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/WhiteSur-light
        - $SNAP/share/themes/WhiteSur-light-blue
        - $SNAP/share/themes/WhiteSur-light-purple
        - $SNAP/share/themes/WhiteSur-light-pink
        - $SNAP/share/themes/WhiteSur-light-red
        - $SNAP/share/themes/WhiteSur-light-orange
        - $SNAP/share/themes/WhiteSur-light-yellow
        - $SNAP/share/themes/WhiteSur-light-green
        - $SNAP/share/themes/WhiteSur-light-grey
        - $SNAP/share/themes/WhiteSur-light-alt
        - $SNAP/share/themes/WhiteSur-light-alt-blue
        - $SNAP/share/themes/WhiteSur-light-alt-purple
        - $SNAP/share/themes/WhiteSur-light-alt-pink
        - $SNAP/share/themes/WhiteSur-light-alt-red
        - $SNAP/share/themes/WhiteSur-light-alt-orange
        - $SNAP/share/themes/WhiteSur-light-alt-yellow
        - $SNAP/share/themes/WhiteSur-light-alt-green
        - $SNAP/share/themes/WhiteSur-light-alt-grey
        - $SNAP/share/themes/WhiteSur-light-solid
        - $SNAP/share/themes/WhiteSur-light-solid-blue
        - $SNAP/share/themes/WhiteSur-light-solid-purple
        - $SNAP/share/themes/WhiteSur-light-solid-pink
        - $SNAP/share/themes/WhiteSur-light-solid-red
        - $SNAP/share/themes/WhiteSur-light-solid-orange
        - $SNAP/share/themes/WhiteSur-light-solid-yellow
        - $SNAP/share/themes/WhiteSur-light-solid-green
        - $SNAP/share/themes/WhiteSur-light-solid-grey
        - $SNAP/share/themes/WhiteSur-light-solid-alt
        - $SNAP/share/themes/WhiteSur-light-solid-alt-blue
        - $SNAP/share/themes/WhiteSur-light-solid-alt-purple
        - $SNAP/share/themes/WhiteSur-light-solid-alt-pink
        - $SNAP/share/themes/WhiteSur-light-solid-alt-red
        - $SNAP/share/themes/WhiteSur-light-solid-alt-orange
        - $SNAP/share/themes/WhiteSur-light-solid-alt-yellow
        - $SNAP/share/themes/WhiteSur-light-solid-alt-green
        - $SNAP/share/themes/WhiteSur-light-solid-alt-grey
        - $SNAP/share/themes/WhiteSur-dark
        - $SNAP/share/themes/WhiteSur-dark-blue
        - $SNAP/share/themes/WhiteSur-dark-purple
        - $SNAP/share/themes/WhiteSur-dark-pink
        - $SNAP/share/themes/WhiteSur-dark-red
        - $SNAP/share/themes/WhiteSur-dark-orange
        - $SNAP/share/themes/WhiteSur-dark-yellow
        - $SNAP/share/themes/WhiteSur-dark-green
        - $SNAP/share/themes/WhiteSur-dark-grey
        - $SNAP/share/themes/WhiteSur-dark-alt
        - $SNAP/share/themes/WhiteSur-dark-alt-blue
        - $SNAP/share/themes/WhiteSur-dark-alt-purple
        - $SNAP/share/themes/WhiteSur-dark-alt-pink
        - $SNAP/share/themes/WhiteSur-dark-alt-red
        - $SNAP/share/themes/WhiteSur-dark-alt-orange
        - $SNAP/share/themes/WhiteSur-dark-alt-yellow
        - $SNAP/share/themes/WhiteSur-dark-alt-green
        - $SNAP/share/themes/WhiteSur-dark-alt-grey
        - $SNAP/share/themes/WhiteSur-dark-solid
        - $SNAP/share/themes/WhiteSur-dark-solid-blue
        - $SNAP/share/themes/WhiteSur-dark-solid-purple
        - $SNAP/share/themes/WhiteSur-dark-solid-pink
        - $SNAP/share/themes/WhiteSur-dark-solid-red
        - $SNAP/share/themes/WhiteSur-dark-solid-orange
        - $SNAP/share/themes/WhiteSur-dark-solid-yellow
        - $SNAP/share/themes/WhiteSur-dark-solid-green
        - $SNAP/share/themes/WhiteSur-dark-solid-grey
        - $SNAP/share/themes/WhiteSur-dark-solid-alt
        - $SNAP/share/themes/WhiteSur-dark-solid-alt-blue
        - $SNAP/share/themes/WhiteSur-dark-solid-alt-purple
        - $SNAP/share/themes/WhiteSur-dark-solid-alt-pink
        - $SNAP/share/themes/WhiteSur-dark-solid-alt-red
        - $SNAP/share/themes/WhiteSur-dark-solid-alt-orange
        - $SNAP/share/themes/WhiteSur-dark-solid-alt-yellow
        - $SNAP/share/themes/WhiteSur-dark-solid-alt-grey
        - $SNAP/share/themes/WhiteSur-dark-solid-alt-green
  icon-themes:
    interface: content
    source:
      read:
      - $SNAP/share/icons/WhiteSur
      - $SNAP/share/icons/WhiteSur-cursors
      - $SNAP/share/icons/WhiteSur-dark
      - $SNAP/share/icons/WhiteSur-green
      - $SNAP/share/icons/WhiteSur-green-dark
      - $SNAP/share/icons/WhiteSur-grey
      - $SNAP/share/icons/WhiteSur-grey-dark
      - $SNAP/share/icons/WhiteSur-orange
      - $SNAP/share/icons/WhiteSur-orange-dark
      - $SNAP/share/icons/WhiteSur-pink
      - $SNAP/share/icons/WhiteSur-pink-dark
      - $SNAP/share/icons/WhiteSur-purple
      - $SNAP/share/icons/WhiteSur-purple-dark
      - $SNAP/share/icons/WhiteSur-red
      - $SNAP/share/icons/WhiteSur-red-dark
      - $SNAP/share/icons/WhiteSur-yellow
      - $SNAP/share/icons/WhiteSur-yellow-dark

        
parts:
  whitesur-gtk-theme:
    # See 'snapcraft plugins'
    after: [utils]
    plugin: nil
    source: https://github.com/vinceliuice/WhiteSur-gtk-theme.git
    source-type: git 
    build-packages:
      - sassc
      - libcanberra-gtk-module 
      - libglib2.0-dev
    override-build: |
        snapcraftctl build
        snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
        ./install.sh --theme all\
                     --alt all\
                     --dest $SNAPCRAFT_PART_INSTALL/share/themes && sleep 5 
        $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*

    # icon theme
  whitesur-icon-theme:
    after: [utils]
    plugin: nil
    source: https://github.com/vinceliuice/WhiteSur-icon-theme.git
    source-type: git 
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
        ./install.sh -t all
        mv /usr/share/icons//WhiteSur* $SNAPCRAFT_PART_INSTALL/share/icons
        $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/WhiteSur
      - share/icons/WhiteSur-dark
      - share/icons/WhiteSur-green
      - share/icons/WhiteSur-green-dark
      - share/icons/WhiteSur-grey
      - share/icons/WhiteSur-grey-dark
      - share/icons/WhiteSur-orange
      - share/icons/WhiteSur-orange-dark
      - share/icons/WhiteSur-pink
      - share/icons/WhiteSur-pink-dark
      - share/icons/WhiteSur-purple
      - share/icons/WhiteSur-purple-dark
      - share/icons/WhiteSur-red
      - share/icons/WhiteSur-red-dark
      - share/icons/WhiteSur-yellow
      - share/icons/WhiteSur-yellow-dark

# cursor theme
  whitesur-cursors:
    after: [utils]
    plugin: nil
    source: https://github.com/vinceliuice/WhiteSur-cursors.git
    source-type: git 
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
        cp -pr dist $SNAPCRAFT_PART_INSTALL/share/icons/WhiteSur-cursors
        $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/WhiteSur-cursors

  utils:
    plugin: dump
    source: utils
    prime:
      - .*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
